// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_ten_hands = "CgkIwuqymqUNEAIQDw"; // <GPGSID>
        public const string achievement_smalltime_vandal = "CgkIwuqymqUNEAIQGA"; // <GPGSID>
        public const string achievement_heavyweight = "CgkIwuqymqUNEAIQIg"; // <GPGSID>
        public const string achievement_hit_the_one_in_the_middle = "CgkIwuqymqUNEAIQAw"; // <GPGSID>
        public const string achievement_people_who_live_in_glass_houses = "CgkIwuqymqUNEAIQGg"; // <GPGSID>
        public const string achievement_window_of_opportunity = "CgkIwuqymqUNEAIQBQ"; // <GPGSID>
        public const string achievement_buy_somethin_will_ya = "CgkIwuqymqUNEAIQBg"; // <GPGSID>
        public const string achievement_hand_to_mouth = "CgkIwuqymqUNEAIQEw"; // <GPGSID>
        public const string leaderboard_easy_difficulty__score_attack = "CgkIwuqymqUNEAIQCA"; // <GPGSID>
        public const string achievement_no_quarter_of_a_million = "CgkIwuqymqUNEAIQEQ"; // <GPGSID>
        public const string achievement_easy_street = "CgkIwuqymqUNEAIQAg"; // <GPGSID>
        public const string leaderboard_easy_difficulty = "CgkIwuqymqUNEAIQBw"; // <GPGSID>
        public const string leaderboard_medium_difficulty = "CgkIwuqymqUNEAIQCQ"; // <GPGSID>
        public const string achievement_face_off = "CgkIwuqymqUNEAIQFA"; // <GPGSID>
        public const string achievement_hundred_hand_smack = "CgkIwuqymqUNEAIQEA"; // <GPGSID>
        public const string achievement_nnnnnhhhhh = "CgkIwuqymqUNEAIQAQ"; // <GPGSID>
        public const string achievement_glove_love = "CgkIwuqymqUNEAIQJw"; // <GPGSID>
        public const string achievement_lord_of_socko = "CgkIwuqymqUNEAIQIw"; // <GPGSID>
        public const string achievement_shattered = "CgkIwuqymqUNEAIQGQ"; // <GPGSID>
        public const string achievement_through_the_broken_looking_glass = "CgkIwuqymqUNEAIQGw"; // <GPGSID>
        public const string achievement_breakthrough = "CgkIwuqymqUNEAIQIA"; // <GPGSID>
        public const string achievement_whomped = "CgkIwuqymqUNEAIQIQ"; // <GPGSID>
        public const string achievement_the_glassshard_menagerie = "CgkIwuqymqUNEAIQHA"; // <GPGSID>
        public const string achievement_sock_it_to_em = "CgkIwuqymqUNEAIQHg"; // <GPGSID>
        public const string leaderboard_challenge_mode = "CgkIwuqymqUNEAIQDQ"; // <GPGSID>
        public const string achievement_a_fistful_of_some_kind_of_currency = "CgkIwuqymqUNEAIQJQ"; // <GPGSID>
        public const string achievement_up_and_coming_pugilist = "CgkIwuqymqUNEAIQHQ"; // <GPGSID>
        public const string achievement_raise_that_fist = "CgkIwuqymqUNEAIQJg"; // <GPGSID>
        public const string leaderboard_medium_difficulty__score_attack = "CgkIwuqymqUNEAIQCg"; // <GPGSID>
        public const string achievement_wipe_that_smile_off_their_faces = "CgkIwuqymqUNEAIQFQ"; // <GPGSID>
        public const string achievement_hard_knocks = "CgkIwuqymqUNEAIQBA"; // <GPGSID>
        public const string leaderboard_hard_difficulty = "CgkIwuqymqUNEAIQCw"; // <GPGSID>
        public const string achievement_talk_to_the_hand = "CgkIwuqymqUNEAIQJA"; // <GPGSID>
        public const string achievement_smile_youre_dead = "CgkIwuqymqUNEAIQFw"; // <GPGSID>
        public const string leaderboard_hard_difficulty__score_attack = "CgkIwuqymqUNEAIQDA"; // <GPGSID>
        public const string achievement_punching_upward = "CgkIwuqymqUNEAIQHw"; // <GPGSID>
        public const string achievement_master_of_the_fist = "CgkIwuqymqUNEAIQEg"; // <GPGSID>
        public const string achievement_feeling_pleased_as_punch = "CgkIwuqymqUNEAIQKA"; // <GPGSID>
        public const string achievement_have_a_nice_day_not = "CgkIwuqymqUNEAIQFg"; // <GPGSID>

}

